#!/usr/bin/env ruby
# frozen_string_literal: true

class BoardPos
  attr_accessor :number, :marked

  def initialize(number)
    @number = number
    @marked = false
  end
end

class BingoBoard
  attr_accessor :positions

  GRID_SIZE = 5

  def initialize
    @positions = []
  end

  def self.parse(input)
    board = BingoBoard.new
    input.split("\n").join(' ').split(/\s+/).each do |number|
      board.positions << BoardPos.new(number.to_i)
    end
    board
  end

  def mark(number)
    @positions.filter { |pos| pos.number == number }
              .each { |pos| pos.marked = true }
  end

  def col_won?(number)
    (0...GRID_SIZE)
      .map { |pos| positions[number + (pos * GRID_SIZE)].marked }
      .reduce(true) { |acc, val| acc && val }
  end

  def row_won?(number)
    (0...GRID_SIZE)
      .map { |pos| positions[pos + (number * GRID_SIZE)].marked }
      .reduce(true) { |acc, val| acc && val }
  end

  def won?
    (0...GRID_SIZE).each do |i|
      return true if col_won? i
      return true if row_won? i
    end
    false
  end
end

input = File.read 'input/data.txt'
input_parts = input.split "\n\n"
draw = input_parts[0].split(',').map(&:to_i)

boards = []
last_winner = nil
winner_draw = nil
input_parts[1...input_parts.size].each do |part|
  boards << BingoBoard.parse(part)
end
catch :winner do
  draw.each do |nb|
    won_this_round = []
    boards.each do |board|
      board.mark nb
      if board.won?
        won_this_round << board
        last_winner = board
        winner_draw = nb
      end
    end
    won_this_round.each { |b| boards.delete b }
    throw :winner if boards.empty?
  end
end
if last_winner
  unmarked_sum = last_winner.positions.filter { |pos| !pos.marked }.map(&:number).sum
  result = unmarked_sum * winner_draw
  puts "result: #{result}"
end
