#!/usr/bin/env ruby
# frozen_string_literal: true

Player = Struct.new(:nb, :starting_pos, :wins) do
  def initialize(nb, starting_pos)
    self.nb = nb
    self.starting_pos = starting_pos
    self.wins = 0
  end
end

outcome_counts = { 3 => 1, 4 => 3, 5 => 6, 6 => 7, 7 => 6, 8 => 3, 9 => 1 }

def dirac_dice(dim_count, playerA, scoreA, posA, playerB, scoreB, posB, outcomes)
  if scoreB > 20
    playerB.wins += dim_count
  else
    outcomes.entries.each do |steps, counts|
      new_pos = ((posA + steps - 1) % 10) + 1
      dirac_dice(dim_count * counts, playerB, scoreB, posB, playerA, scoreA + new_pos, new_pos, outcomes)
    end
  end
end

input_lines = File.readlines 'input/data.txt'
players = input_lines.map do |line|
  s = line.split ' '
  Player.new s[1].to_i, s[4].to_i
end

p1 = players[0]
p2 = players[1]

dirac_dice(1, p1, 0, p1.starting_pos, p2, 0, p2.starting_pos, outcome_counts)
puts p1.wins
puts p2.wins
puts "result: #{[p1.wins, p2.wins].max}"
