#!/usr/bin/env ruby
# frozen_string_literal: true

class VentLine
  attr_accessor :pos1, :pos2

  def initialize(pos1, pos2)
    if pos1 > pos2
      @pos1 = pos2
      @pos2 = pos1
    else
      @pos1 = pos1
      @pos2 = pos2
    end
  end

  def intersections(another)
    if horizontal? && another.vertical?
      if pos1.x <= another.pos1.x &&
         another.pos1.x <= pos2.x &&
         another.pos1.y <= pos1.y &&
         pos1.y <= another.pos2.y
        # puts "Intersection at #{another.pos1.x},#{pos1.y}"
        return ["#{another.pos1.x}##{pos1.y}"]
      end
    elsif vertical? && another.horizontal?
      if another.pos1.x <= pos1.x &&
         pos1.x <= another.pos2.x &&
         pos1.y <= another.pos1.y &&
         another.pos1.y <= pos2.y
        # puts "Intersection at #{pos1.x},#{another.pos1.y}"
        return ["#{pos1.x}##{another.pos1.y}"]
      end
    elsif horizontal? && another.horizontal?
      return [] unless pos1.y == another.pos1.y

      if pos2.x >= another.pos1.x && pos1.x <= another.pos2.x
        lower_bound = [pos1.x, another.pos1.x].max
        upper_bound = [pos2.x, another.pos2.x].min
        # puts "Hor.overlap [#{lower_bound}, #{upper_bound}]"
        return (lower_bound..upper_bound).map { |x| "#{x}##{pos1.y}" }
      end
    elsif vertical? && another.vertical?
      return [] unless pos1.x == another.pos1.x

      if pos2.y >= another.pos1.y && pos1.y <= another.pos2.y
        lower_bound = [pos1.y, another.pos1.y].max
        upper_bound = [pos2.y, another.pos2.y].min
        # puts "Vert.overlap [#{lower_bound}, #{upper_bound}]"
        return (lower_bound..upper_bound).map { |y| "#{pos1.x}##{y}" }
      end
    end
    []
  end

  def horizontal?
    pos1.y == pos2.y
  end

  def vertical?
    pos1.x == pos2.x
  end
end

Point = Struct.new(:x, :y) do
  include Comparable

  def self.parse(from)
    parts = from.split(',')
    Point.new(parts[0].to_i, parts[1].to_i)
  end

  def <=>(other)
    return y <=> other.y if x == other.x
    return x <=> other.x if y == other.y

    (x + y) <=> (other.x + other.y)
  end
end

input_lines = File.readlines 'input/data.txt'
vent_lines = []
input_lines.each do |line|
  points = line.split('->').map(&:strip).map { |e| Point.parse e }
  vent_lines << VentLine.new(points[0], points[1])
end
vent_lines = vent_lines.filter { |line| line.horizontal? || line.vertical? }

intersection_counts = Hash.new(0)
vent_lines.each_with_index do |line, index|
  vent_lines[(index + 1)...vent_lines.size].each do |compare_line|
    line.intersections(compare_line).each do |intersection|
      intersection_counts[intersection] += 1
    end
  end
end
# puts intersection_counts.inspect
puts "result: #{intersection_counts.size}"
